spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logintest?characterEncoding=utf-8&userSSL=false
    username: root
    password:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000



  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100

    scheduling:
      pool:
        size: 5

  elasticsearch:
    uris: localhost:9200


  servlet:
    context-path:


mybatis-plus:
  global-config:
    db-config:
      id-type: none
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 443
#  ssl:
#    key-store: classpath:tsky31.cn.jks
#    key-password: z7r25s7g7tj
#    key-store-type: JKS
#    enabled: true
